package stockbroker.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 * Plots the bar chart for the performance of the portfolio over a selected period of time. This
 * class helps in plotting the graph based on the values generated by the performance evaluation.
 */
public class PerformanceChart extends JPanel {

  private double[] values;
  private String[] dates;
  private String title;

  /**
   * Constructor for the performance chart class. Takes in performance data is arrays of values and
   * the dates.
   *
   * @param values performance values.
   * @param dates  distribution of dates over a period.
   * @param title  of the graph.
   */
  public PerformanceChart(double[] values, String[] dates, String title) {
    this.dates = dates;
    this.values = values;
    this.title = title;
  }

  /**
   * Creates the bar chart for the performance of the portfolio.
   *
   * @param graphics the <code>Graphics</code> object to protect.
   */
  public void paintComponent(Graphics graphics) {
    super.paintComponent(graphics);
    if (values == null || values.length == 0) {
      return;
    }
    double minValue = 0;
    double maxValue = 0;
    for (int i = 0; i < values.length; i++) {
      if (minValue > values[i]) {
        minValue = values[i];
      }
      if (maxValue < values[i]) {
        maxValue = values[i];
      }
    }
    Dimension dim = getSize();
    int clientWidth = dim.width;
    int clientHeight = dim.height;
    int barWidth = clientWidth / values.length;
    Font titleFont = new Font("TimesRoman", Font.BOLD, 15);
    FontMetrics titleFontMetrics = graphics.getFontMetrics(titleFont);
    Font labelFont = new Font("TimesRoman", Font.PLAIN, 10);
    FontMetrics labelFontMetrics = graphics.getFontMetrics(labelFont);
    int titleWidth = titleFontMetrics.stringWidth(title);
    int q = titleFontMetrics.getAscent();
    int p = (clientWidth - titleWidth) / 2;
    graphics.setFont(titleFont);
    graphics.drawString(title, p, q);
    int top = titleFontMetrics.getHeight();
    int bottom = labelFontMetrics.getHeight();
    if (maxValue == minValue) {
      return;
    }
    double scale = (clientHeight - top - bottom) / (maxValue - minValue);
    q = clientHeight - labelFontMetrics.getDescent();
    graphics.setFont(labelFont);
    for (int j = 0; j < values.length; j++) {
      int valueP = j * barWidth + 1;
      int valueQ = top;
      int height = (int) (values[j] * scale);
      if (values[j] >= 0) {
        valueQ += (int) ((maxValue - values[j]) * scale);
      } else {
        valueQ += (int) (maxValue * scale);
        height = -height;
      }
      graphics.setColor(Color.cyan);
      graphics.fillRect(valueP, valueQ, barWidth - 3, height);
      graphics.setColor(Color.black);
      graphics.drawRect(valueP, valueQ, barWidth - 3, height);
      int labelWidth = labelFontMetrics.stringWidth(dates[j]);
      p = j * barWidth + (barWidth - labelWidth) / 2;
      graphics.drawString(dates[j], p, q);
    }
  }
}
